name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: ["adopt@1.8", "adopt@1.11"]
        scala: ["2.13.4"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.m2
            ~/.cache
          key: sbt-blended-zio-cache-${{ matrix.java }}-${{ matrix.scala }}
      - name: Lint code
        run: sbt check
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test

  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref.startsWith('refs/tags')
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@v3
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          PGP_SECRET: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_SBT_CREDENTIALS }}
          SONATYPE_USERNAME: "atooni"
