name: Website

on:
  push:
    branches: [docs]
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: |
          wget https://gnupg.org/ftp/gcrypt/gnupg/gnupg-1.4.23.tar.bz2
          bzip2 -d gnupg-1.4.23.tar.bz2
          tar xvf gnupg-1.4.23.tar
          cd gnupg-1.4.23

          ./configure

          make

          ./gpg --version

      - run: |
          sbt docs/unidoc docs/mdoc
          cd website 
          npm i 
          yarn deploy
        env:
          GIT_USER: atooni
          USE_SSH: true
          GIT_DEPLOY_KEY: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
