name: Website

on:
  push:
    branches: [docs]
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@master
      - run: |
          sbt docs/unidoc docs/mdoc
          cd website 
          npm i 
          yarn deploy
        env:
          GIT_USER: atooni
          USE_SSH: true
          GIT_DEPLOY_KEY: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
