name: Website

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@v3
      - run: |
          sbt doc docs/mdoc
          cd website 
          yarn deploy
        env:
          GIT_USER: atooni
          GIT_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
